
services:

    block.dependency_injection.types:
        class: 'Cms\BlockBundle\Service\Registry\DependencyInjection\DependencyInjectionBlockTypes'
        public: true
        arguments:
            - ""
            - ""

    block.dependency_injection.controllers:
        class: 'Cms\BlockBundle\Service\Registry\DependencyInjection\DependencyInjectionBlockControllers'
        public: true
        arguments:
            - ""
            - ""