
services:

    block.data_transformers:
        class: 'Cms\BlockBundle\Service\BlockDataTransformers'
        public: true

    block.data_transformers.finder:
        class: 'Cms\BlockBundle\Service\Finder\DataTransformersFinder'
        public: true
        arguments:
            - "@block.annotations.finder"
            - "@block.data_transformers"

    block.data_transformer.entity:
        class: 'Cms\BlockBundle\DataTransformer\EntityTransformer'
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@block.annotations.finder"
        tags:
            - { name: block.data_transformer, alias: 'entity' }

    block.data_transformer.type:
        class: 'Cms\BlockBundle\DataTransformer\TypeTransformer'
        public: true
        arguments:
            - "@block.factory"
        tags:
            - { name: block.data_transformer, alias: 'type' }

    block.data_transformer.collection:
        class: 'Cms\BlockBundle\DataTransformer\CollectionTransformer'
        public: true
        arguments:
            - "@block.factory"
            - "@block.data_transformer.type"
            - "@block.annotations.finder"
        tags:
            - { name: block.data_transformer, alias: 'collection' }

    block.data_transformer.assoc_entity_to_type:
        class: 'Cms\BlockBundle\DataTransformer\AssocEntityToTypeTransformer'
        public: true
        arguments:
            - "@block.factory"
        tags:
            - { name: block.data_transformer, alias: 'assoc_entity_to_type' }

