
services:

    block.entity.property:
        class: 'Cms\BlockBundle\Service\Entity\BlockEntityProperty'
        public: true
        arguments:
            - "@block.data_transformers"

    block.entity_manager:
        class: 'Cms\BlockBundle\Service\Entity\BlockEntityManager'
        public: true
        arguments:
            - "@block.entity.transformer"
            - "@block.entity.property"
            - "@serializer"
            - "@block.annotations.finder"
            - "@block.entity_manager.indexation"

    block.entity.transformer:
        class: 'Cms\BlockBundle\Service\Entity\BlockEntityTransformer'
        public: true
        arguments:
            - "@block.entity.property"
            - "@block.data_transformers.finder"

    block.event_listener:
        class: 'Cms\BlockBundle\EventListener\BlockListener'
        arguments:
            - "@block.factory"
            - "@block.entity_manager"
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
            - { name: doctrine.event_listener, event: postFlush, lazy: true }
            - { name: doctrine.event_listener, event: postLoad, lazy: true }

    block.entity_manager.indexation:
        class: 'Cms\BlockBundle\Service\Entity\BlockIndexationManager'
        public: true
        arguments:
            - "@serializer"
            - "@doctrine.orm.entity_manager"
