
services:

    block.registries:
        class: 'Cms\BlockBundle\Service\BlockRegistries'
        public: true

    # REGISTRY

    block.registry.types:
        class: 'Cms\BlockBundle\Service\Registry\BlockTypesRegistry'
        public: true
        arguments:
            - "@block.dependency_injection.types"
            - "@block.resolved_type.factory"
        tags:
            - { name: block.registry, alias: 'type' }

    block.registry.controllers:
        class: 'Cms\BlockBundle\Service\Registry\BlockControllersRegistry'
        public: true
        arguments:
            - "@block.dependency_injection.controllers"
        tags:
            - { name: block.registry, alias: 'controller' }
