imports:
    - { resource: 'packages/dependence_injection.yaml' }
    - { resource: 'packages/data_transformers.yaml' }
    - { resource: 'packages/registry.yaml' }
    - { resource: 'packages/entity.yaml' }

services:

    BlockBundle\Service\BlockFactory: '@block.factory'

    block.twig.extension:
        class: 'BlockBundle\Twig\BlockExtension'
        public: true
        arguments:
            - "@block.renderer"
            - "@block.factory"
        tags:
            - { name: twig.extension }

    block.serializer:
        class: 'Symfony\Component\Serializer\Serializer'
        public: true
        arguments:
            - ["@block.serializer.normalizer"]
            - ["@block.serializer.encoder.array"]

    block.serializer.normalizer:
        class: 'BlockBundle\Serializer\Normalizer\BlockNormalizer'
        public: true
        arguments:
            - "@serializer.normalizer.object"
            - "@block.entity.transformer"

    block.serializer.encoder.array:
        class: 'BlockBundle\Serializer\Encoder\ArrayEncoder'
        public: true

    block.factory:
        class: 'BlockBundle\Service\BlockFactory'
        public: true
        arguments:
            - "@block.registries"
            - "@block.entity_manager"
            - "@form.factory"

    block.resolved_type.factory:
        class: 'BlockBundle\Service\ResolvedBlockTypeFactory'
        public: true

    block.forms.abstract:
        class: 'BlockBundle\Service\AbstractBlockForms'
        abstract:  true
        public: true
        arguments:
            - "@block.registry.types"
            - "@block.annotations.finder"

    block.forms:
        class: 'BlockBundle\Service\BlockForms'
        parent: 'block.forms.abstract'

    block.form_type.abstract_collection:
        class: 'BlockBundle\Form\AbstractBlockCollectionType'
        abstract:  true
        public: true
        arguments:
            - "@block.forms"
            - "@service_container"

    block.form_type.collection:
        class: 'BlockBundle\Form\BlockCollectionType'
        parent: 'block.form_type.abstract_collection'
        tags: [form.type]

    block.form_type.parent:
        class: 'BlockBundle\Form\BlockParentType'
        tags: [form.type]

    block.renderer:
        class: 'BlockBundle\Service\BlockRenderer'
        public: true
        arguments:
            - "@request_stack"
            - "@block.factory"
            - "@templating"
            - "%block.themes%"

    block.annotations.finder:
        class: 'BlockBundle\Service\Finder\AnnotationsFinder'
        public: true