block_render:
    path:  /block/{name}/{id}/render
    controller: Cms\BlockBundle\Controller\BlockController::render
    requirements:
        name: "[\\w]+"
        id: "[\\w]+"

block_custom:
    path:  /block/{name}/{id}/{action}
    controller: Cms\BlockBundle\Controller\BlockController::custom
    requirements:
        name: "[\\w]+"
        id: "[\\w]+"
        action: ".+"