block_load:
    path:  /block/{name}/{id}/load
    controller: Cms\BlockBundle\Controller\BlockController::loadView
    requirements:
        name: "[\\w]+"
        id: "[\\w]+"

block_action:
    path:  /block/{name}/{id}/{action}
    controller: Cms\BlockBundle\Controller\BlockController::action
    requirements:
        name: "[\\w]+"
        id: "[\\w]+"
        action: ".+"